#! /bin/bash
### Run with sudo ###

# Setup sources.list
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

# Set up keys
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

# Install
sudo apt-get update

sudo apt-get install ros-kinetic-ros-base

# Initialize rosdep
sudo rosdep init
rosdep update

# Environment setup
echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc

# Dependencies for building packages, might not be needed
#sudo apt python-rosinstall python-rosinstall-generator python-wstool build-essential

# Create ros workspace
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/
catkin_make
source devel/setup.bash

#Press a key to reboot
read -s -n 1 -p "Installation complete, press any key to reboot"
sudo reboot
